# =========================================================================
# GLOBAL CONFIGURATION
# =========================================================================

resolver 127.0.0.11 valid=30s;

proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;


# =========================================================================
# SERVICE CONFIGURATION
# =========================================================================

server {
    listen 8080;
    server_name raizuma.de;

    location / {
        set $upstream_web web:80;
        proxy_pass http://$upstream_web;
    }
}

server {
    listen 8080;
    server_name api.raizuma.de;

    location / {
        set $upstream_api api:80;
        proxy_pass http://$upstream_api;
    }
}

server {
    listen 8080;
    server_name auth.raizuma.de;

    location / {
        set $upstream_auth auth:80;
        proxy_pass http://$upstream_auth;
    }
}

server {
    listen 8080;
    server_name account.raizuma.de;

    location / {
        set $upstream_account account:80;
        proxy_pass http://$upstream_account;
    }
}

server {
    listen 8080;
    server_name admin.raizuma.de;

    location / {
        set $upstream_admin admin:80;
        proxy_pass http://$upstream_admin;
    }
}
